export const italianDishes = [
  {
    id: 1,
    name: "Margherita Pizza",
    italian: "Pizza Margherita",
    category: "Pizza",
    time: "30 min",
    difficulty: "Easy",
    tags: ["cheesy", "classic", "vegetarian", "italian"],
    emoji: "🍕",
    color: "#E63946",
    description:
      "Classic Italian pizza topped with tomato sauce, mozzarella, and basil.",
    ingredients: [
      "Pizza dough",
      "Tomato sauce",
      "Fresh mozzarella",
      "Fresh basil leaves",
      "Olive oil",
      "Salt",
    ],
    steps: [
      "Roll pizza dough evenly.",
      "Spread tomato sauce.",
      "Add mozzarella slices.",
      "Bake at 250°C for 12 minutes.",
      "Top with basil and olive oil.",
    ],
  },

  {
    id: 2,
    name: "Pasta Carbonara",
    italian: "Spaghetti Carbonara",
    category: "Pasta",
    time: "25 min",
    difficulty: "Medium",
    tags: ["creamy", "pasta", "italian"],
    emoji: "🍝",
    color: "#F4A261",
    description:
      "Creamy Roman pasta made with eggs, cheese, pancetta, and pepper.",
    ingredients: [
      "Spaghetti",
      "Eggs",
      "Parmesan cheese",
      "Pancetta",
      "Black pepper",
      "Salt",
    ],
    steps: [
      "Cook spaghetti until al dente.",
      "Cook pancetta until crispy.",
      "Mix eggs and parmesan.",
      "Combine hot pasta with pancetta and egg mixture.",
      "Serve with black pepper.",
    ],
  },

  {
    id: 3,
    name: "Lasagna",
    italian: "Lasagna Classica",
    category: "Pasta",
    time: "1 hr",
    difficulty: "Hard",
    tags: ["baked", "cheesy", "comfort food"],
    emoji: "🧀",
    color: "#C1121F",
    description:
      "Layered pasta baked with meat sauce, béchamel, and cheese.",
    ingredients: [
      "Lasagna sheets",
      "Minced meat",
      "Tomato sauce",
      "Mozzarella cheese",
      "Béchamel sauce",
      "Parmesan cheese",
    ],
    steps: [
      "Cook meat with tomato sauce.",
      "Prepare béchamel sauce.",
      "Layer pasta sheets, meat sauce, béchamel, cheese.",
      "Repeat layers.",
      "Bake for 40 minutes.",
    ],
  },

  {
    id: 4,
    name: "Risotto",
    italian: "Risotto ai Funghi",
    category: "Rice",
    time: "40 min",
    difficulty: "Medium",
    tags: ["creamy", "rice", "mushroom"],
    emoji: "🍚",
    color: "#D9BF77",
    description:
      "Creamy Italian rice dish cooked slowly with broth and mushrooms.",
    ingredients: [
      "Arborio rice",
      "Mushrooms",
      "Vegetable broth",
      "Parmesan cheese",
      "Butter",
      "Onion",
    ],
    steps: [
      "Sauté onion and mushrooms.",
      "Add rice and toast lightly.",
      "Slowly add broth while stirring.",
      "Cook until creamy.",
      "Finish with butter and parmesan.",
    ],
  },

  {
    id: 5,
    name: "Tiramisu",
    italian: "Tiramisù",
    category: "Dessert",
    time: "45 min",
    difficulty: "Medium",
    tags: ["dessert", "coffee", "sweet"],
    emoji: "🍰",
    color: "#6F4E37",
    description:
      "Classic coffee-flavored Italian dessert layered with mascarpone cream.",
    ingredients: [
      "Ladyfingers",
      "Coffee",
      "Mascarpone cheese",
      "Cocoa powder",
      "Sugar",
      "Eggs",
    ],
    steps: [
      "Dip ladyfingers in coffee.",
      "Layer mascarpone cream and biscuits.",
      "Repeat layers.",
      "Dust cocoa powder.",
      "Chill before serving.",
    ],
  },

  {
    id: 6,
    name: "Bruschetta",
    italian: "Bruschetta al Pomodoro",
    category: "Starter",
    time: "15 min",
    difficulty: "Easy",
    tags: ["starter", "bread", "tomato"],
    emoji: "🍅",
    color: "#E76F51",
    description:
      "Toasted bread topped with fresh tomatoes, garlic, and basil.",
    ingredients: [
      "Bread slices",
      "Tomatoes",
      "Garlic",
      "Olive oil",
      "Basil",
      "Salt",
    ],
    steps: [
      "Toast bread slices.",
      "Mix tomatoes, garlic, basil.",
      "Top bread with mixture.",
      "Drizzle olive oil.",
      "Serve fresh.",
    ],
  },

  {
    id: 7,
    name: "Focaccia",
    italian: "Focaccia",
    category: "Bread",
    time: "2 hrs",
    difficulty: "Medium",
    tags: ["bread", "baked", "olive oil"],
    emoji: "🥖",
    color: "#C08457",
    description:
      "Soft Italian flatbread flavored with olive oil and herbs.",
    ingredients: [
      "Flour",
      "Yeast",
      "Olive oil",
      "Rosemary",
      "Salt",
      "Water",
    ],
    steps: [
      "Prepare dough and let rise.",
      "Spread in baking tray.",
      "Top with olive oil and rosemary.",
      "Bake until golden.",
      "Serve warm.",
    ],
  },

  {
    id: 8,
    name: "Gnocchi",
    italian: "Gnocchi di Patate",
    category: "Pasta",
    time: "50 min",
    difficulty: "Medium",
    tags: ["potato", "soft", "italian"],
    emoji: "🥔",
    color: "#E9C46A",
    description:
      "Soft potato dumplings served with sauce or butter.",
    ingredients: [
      "Potatoes",
      "Flour",
      "Egg",
      "Salt",
      "Butter",
    ],
    steps: [
      "Boil and mash potatoes.",
      "Mix with flour and egg.",
      "Shape into dumplings.",
      "Boil until floating.",
      "Serve with butter or sauce.",
    ],
  },

  {
    id: 9,
    name: "Panna Cotta",
    italian: "Panna Cotta",
    category: "Dessert",
    time: "20 min",
    difficulty: "Easy",
    tags: ["dessert", "creamy", "sweet"],
    emoji: "🍮",
    color: "#FFF3B0",
    description:
      "Smooth Italian cream dessert topped with berry sauce.",
    ingredients: [
      "Cream",
      "Sugar",
      "Vanilla",
      "Gelatin",
      "Berry sauce",
    ],
    steps: [
      "Heat cream and sugar.",
      "Add gelatin.",
      "Pour into molds.",
      "Chill until set.",
      "Serve with berry sauce.",
    ],
  },

  {
    id: 10,
    name: "Minestrone Soup",
    italian: "Minestrone",
    category: "Soup",
    time: "45 min",
    difficulty: "Easy",
    tags: ["healthy", "vegetable", "soup"],
    emoji: "🥣",
    color: "#8AB17D",
    description:
      "Traditional Italian vegetable soup with beans and pasta.",
    ingredients: [
      "Carrots",
      "Beans",
      "Pasta",
      "Tomatoes",
      "Celery",
      "Vegetable broth",
    ],
    steps: [
      "Cook vegetables.",
      "Add broth and beans.",
      "Add pasta.",
      "Simmer until tender.",
      "Serve hot.",
    ],
  },

  {
    id: 11,
    name: "Ravioli",
    italian: "Ravioli",
    category: "Pasta",
    time: "1 hr",
    difficulty: "Hard",
    tags: ["stuffed", "pasta", "italian"],
    emoji: "🥟",
    color: "#D4A373",
    description:
      "Stuffed pasta pockets filled with cheese or meat.",
    ingredients: [
      "Pasta dough",
      "Ricotta cheese",
      "Spinach",
      "Parmesan",
      "Tomato sauce",
    ],
    steps: [
      "Prepare filling.",
      "Roll pasta sheets.",
      "Fill and seal ravioli.",
      "Boil until cooked.",
      "Serve with sauce.",
    ],
  },

  {
    id: 12,
    name: "Caprese Salad",
    italian: "Insalata Caprese",
    category: "Salad",
    time: "10 min",
    difficulty: "Easy",
    tags: ["fresh", "healthy", "salad"],
    emoji: "🥗",
    color: "#2A9D8F",
    description:
      "Fresh mozzarella, tomatoes, and basil drizzled with olive oil.",
    ingredients: [
      "Tomatoes",
      "Mozzarella",
      "Basil",
      "Olive oil",
      "Salt",
    ],
    steps: [
      "Slice tomatoes and mozzarella.",
      "Arrange alternately.",
      "Top with basil.",
      "Drizzle olive oil.",
      "Season and serve.",
    ],
  },

  {
    id: 13,
    name: "Calzone",
    italian: "Calzone",
    category: "Pizza",
    time: "35 min",
    difficulty: "Medium",
    tags: ["stuffed", "pizza", "baked"],
    emoji: "🥙",
    color: "#BC6C25",
    description:
      "Folded pizza stuffed with cheese, sauce, and fillings.",
    ingredients: [
      "Pizza dough",
      "Mozzarella",
      "Tomato sauce",
      "Ham",
      "Olive oil",
    ],
    steps: [
      "Roll pizza dough.",
      "Add fillings on one side.",
      "Fold and seal.",
      "Bake until golden.",
      "Serve hot.",
    ],
  },

  {
    id: 14,
    name: "Osso Buco",
    italian: "Osso Buco",
    category: "Main Course",
    time: "2 hrs",
    difficulty: "Hard",
    tags: ["meat", "slow cooked", "italian"],
    emoji: "🍖",
    color: "#9C6644",
    description:
      "Slow-braised veal shanks cooked with vegetables and wine.",
    ingredients: [
      "Veal shanks",
      "Onion",
      "Carrot",
      "Celery",
      "Tomato paste",
      "White wine",
    ],
    steps: [
      "Brown veal shanks.",
      "Cook vegetables.",
      "Add wine and tomato paste.",
      "Simmer slowly for 2 hours.",
      "Serve warm.",
    ],
  },

  {
    id: 15,
    name: "Gelato",
    italian: "Gelato",
    category: "Dessert",
    time: "4 hrs",
    difficulty: "Medium",
    tags: ["ice cream", "sweet", "cold"],
    emoji: "🍨",
    color: "#FFB5A7",
    description:
      "Rich and creamy Italian-style ice cream.",
    ingredients: [
      "Milk",
      "Cream",
      "Sugar",
      "Vanilla",
      "Chocolate",
    ],
    steps: [
      "Heat milk and sugar.",
      "Add flavoring.",
      "Cool mixture.",
      "Churn until creamy.",
      "Freeze before serving.",
    ],
  },
];